### PR TITLE
Use correct GOLD variable in Makefile. Fix typo.

### PR DESCRIPTION
**Pull request by practicalswift**
Small cleanups:
* Use correct `GOLD` variable in Makefile.
* Fix typo.

### CODE REVIEW

**Comment by withzombies** [comment]
Why'd you close this pull request?

**Comment by practicalswift** [comment]
@withzombies Not worth the CLA hassle :-)

**Comment by withzombies** [comment]
is there a way we could make the CLA process more streamlined? I'm pretty sure it's just a single click.

**Comment by dguido** [comment]
Eh, I'm not sure we care about the CLA for this repo. I just turned it off (it's on all Trail of Bits repos in our organization by default).

**Comment by dguido** [comment]
But, I do want to hear your answer to Ryan's question.

**Comment by practicalswift** [comment]
@withzombies First: I love Trail of Bits and the excellent work you do! Second: I never complete CLA:s so I didn't take time to evaluate if this specific CLA process was easy TBH :-)

**Pull request merged**
